### PR TITLE
Move TestFest Events Results

### PR DESCRIPTION
**Pull request by jmudge**
Results data relocated to https://www.openmobilealliance.org/test_events/

### CODE REVIEW

**Comment by jpradocueva** [comment]
@jmudge I have some comments:

* we should also insert a new column for the Test Event (see screenshot)
* I have checked the name of the files in the FTP e.g. for TF-31 the document file name can be seen in this link: https://openmobilealliance.org/test_events/TF-31/
* Should we change the file name from `TestFest Summary Document.pdf` to something that contains the date and location e.g. `Dusseldorf-TestFest-Summary-Nov-2015`? In this way, if this document is downloaded the file name contains the information. Unfortunately, inside of the document the location is not listed. 

What do you think?

image

**Review by jpradocueva — COMMENTED** [review]
@jmudge I have added a comment in the `conversation`, suggesting adding a column with the `TesFest Event` or `Number` if the space is an issue, and updating the file name of a few Test Results documents by adding location and date. The location is not inside of the file.
Thanks

**Comment by jmudge** [comment]
@joaquin the documents could probably be renamed without people objecting. Some many have saved links with the current filenames but it is unlikely that many people are interested in years old test results. If you want all the documents to be renamed then please provide a suitable naming schema that can also be applied to:
- directories containing multiple summary data files e.g. for different ETSs
- all of the Product Listing files. Note that the link names listed on web page https://guidelines.openmobilealliance.org/listing/ include characters that are not allowed in filenames. Those link names also include many space characters that are not good practice to include in filenames.

**Comment by jpradocueva** [comment]
@jmudge In my view, I think that there were just a few documents, less than 4 or 5 that have a very generic name.  I see an improvement if they are renamed as the name on the file name doesn't say what it is and some of the suggested information is not even inside of the file.
In any way, I leave it up to you the final decision. We have other pending tasks to do and these documents are old. Going forward we will have a name schema for this information.

**Comment by jmudge** [comment]
@jpradocueva the new TF Event column has been added to the PR.

There seem to be aprox. 90 TestFest results files that would need to be renamed. The example filename above is not comprehensive; we would need a suitable naming schema first.

**Pull request merged**
